// ABOUTME: Keyword-to-emoji mapping for contextual emoji reactions
// ABOUTME: Scans word chunks for matches and returns appropriate emoji

const EMOJI_MAP: Record<string, string> = {
  // --- Positive emotions / hype ---
  love: "❤️",
  heart: "❤️",
  loved: "❤️",
  loving: "❤️",
  amazing: "🔥",
  fire: "🔥",
  hot: "🔥",
  awesome: "🔥",
  incredible: "🔥",
  insane: "🔥",
  lit: "🔥",
  flames: "🔥",
  epic: "🔥",
  legendary: "🔥",
  goat: "🐐",
  greatest: "🐐",
  best: "🐐",
  perfect: "💯",
  hundred: "💯",
  percent: "💯",
  absolutely: "💯",
  exactly: "💯",
  happy: "😊",
  glad: "😊",
  joy: "😊",
  smile: "😊",
  blessed: "🙏",
  grateful: "🙏",
  thankful: "🙏",
  thanks: "🙏",
  thank: "🙏",
  pray: "🙏",
  god: "🙏",
  beautiful: "✨",
  gorgeous: "✨",
  stunning: "✨",
  pretty: "✨",
  excited: "🎉",
  exciting: "🎉",
  celebrate: "🎉",
  celebration: "🎉",
  party: "🎉",
  congratulations: "🎉",
  congrats: "🎉",
  proud: "🥹",
  emotional: "🥹",
  crying: "🥹",
  tears: "🥹",
  wholesome: "🥹",

  // --- Money / business ---
  money: "💰",
  cash: "💰",
  rich: "💰",
  dollar: "💰",
  dollars: "💰",
  million: "💰",
  billion: "💰",
  profit: "💰",
  revenue: "💰",
  salary: "💰",
  wealth: "💰",
  income: "💰",
  paid: "💰",
  expensive: "💰",
  invest: "📈",
  investing: "📈",
  investment: "📈",
  growth: "📈",
  grow: "📈",
  growing: "📈",
  increase: "📈",
  rising: "📈",
  stock: "📈",
  stocks: "📈",
  market: "📈",
  business: "💼",
  company: "💼",
  startup: "🚀",
  launch: "🚀",
  launched: "🚀",
  launching: "🚀",
  rocket: "🚀",
  skyrocket: "🚀",
  moon: "🚀",
  brand: "💼",
  entrepreneur: "💼",

  // --- Humor / reactions ---
  laugh: "😂",
  laughing: "😂",
  funny: "😂",
  hilarious: "😂",
  joke: "😂",
  lol: "😂",
  comedy: "😂",
  ridiculous: "😂",
  wow: "😮",
  shocked: "😮",
  shocking: "😮",
  surprise: "😮",
  surprised: "😮",
  unbelievable: "😮",
  crazy: "🤯",
  mind: "🤯",
  blown: "🤯",
  mindblowing: "🤯",
  bonkers: "🤯",
  wild: "🤯",
  cool: "😎",
  sick: "😎",
  smooth: "😎",
  savage: "😎",
  boss: "😎",
  badass: "😎",
  dude: "😎",
  chill: "😎",
  vibe: "😎",
  vibes: "😎",
  sus: "🤨",
  suspicious: "🤨",
  doubt: "🤨",
  really: "🤨",
  seriously: "🤨",
  cap: "🧢",
  lying: "🧢",
  fake: "🧢",
  dead: "💀",
  dying: "💀",
  kill: "💀",
  killed: "💀",
  rip: "💀",
  skull: "💀",
  bruh: "💀",
  cringe: "😬",
  awkward: "😬",
  embarrassing: "😬",
  yikes: "😬",
  oops: "😬",
  clown: "🤡",
  stupid: "🤡",
  dumb: "🤡",
  fool: "🤡",
  idiot: "🤡",

  // --- Strength / motivation ---
  strong: "💪",
  power: "💪",
  powerful: "💪",
  strength: "💪",
  muscle: "💪",
  grind: "💪",
  grinding: "💪",
  hustle: "💪",
  hustling: "💪",
  workout: "💪",
  gym: "💪",
  training: "💪",
  discipline: "💪",
  unstoppable: "💪",
  fighter: "💪",
  fight: "💪",
  fighting: "💪",
  win: "🏆",
  winner: "🏆",
  winning: "🏆",
  champion: "🏆",
  champions: "🏆",
  success: "🏆",
  successful: "🏆",
  trophy: "🏆",
  victory: "🏆",
  king: "👑",
  queen: "👑",
  crown: "👑",
  royal: "👑",
  reign: "👑",
  dominant: "👑",

  // --- Thinking / learning ---
  think: "🤔",
  thinking: "🤔",
  question: "🤔",
  wonder: "🤔",
  wondering: "🤔",
  curious: "🤔",
  hmm: "🤔",
  maybe: "🤔",
  probably: "🤔",
  imagine: "🤔",
  learn: "📚",
  learning: "📚",
  study: "📚",
  studying: "📚",
  book: "📚",
  books: "📚",
  read: "📚",
  reading: "📚",
  knowledge: "🧠",
  brain: "🧠",
  smart: "🧠",
  intelligent: "🧠",
  genius: "🧠",
  strategy: "🧠",
  idea: "💡",
  ideas: "💡",
  creative: "💡",
  creativity: "💡",
  innovation: "💡",
  solution: "💡",
  breakthrough: "💡",
  discover: "💡",
  discovered: "💡",

  // --- Warnings / negatives ---
  danger: "⚠️",
  dangerous: "⚠️",
  warning: "⚠️",
  careful: "⚠️",
  caution: "⚠️",
  risk: "⚠️",
  risky: "⚠️",
  wrong: "❌",
  mistake: "❌",
  mistakes: "❌",
  never: "❌",
  dont: "❌",
  stop: "🛑",
  wait: "🛑",
  hold: "🛑",
  pause: "🛑",
  bad: "👎",
  terrible: "👎",
  worst: "👎",
  horrible: "👎",
  awful: "👎",
  hate: "👎",
  trash: "🗑️",
  garbage: "🗑️",
  waste: "🗑️",
  useless: "🗑️",
  scam: "🚩",
  fraud: "🚩",
  toxic: "🚩",
  avoid: "🚩",
  scary: "😱",
  terrifying: "😱",
  horror: "😱",
  nightmare: "😱",
  fear: "😱",
  afraid: "😱",
  freaking: "😱",
  angry: "😤",
  mad: "😤",
  furious: "😤",
  rage: "😤",
  pissed: "😤",
  annoying: "😤",
  frustrated: "😤",
  sad: "😢",
  depressed: "😢",
  depression: "😢",
  lonely: "😢",
  heartbreak: "💔",
  heartbroken: "💔",
  broken: "💔",
  lost: "💔",
  pain: "💔",
  hurt: "💔",

  // --- Actions / states ---
  new: "✨",
  magic: "✨",
  magical: "✨",
  sparkle: "✨",
  shine: "✨",
  shining: "✨",
  glow: "✨",
  secret: "🤫",
  secrets: "🤫",
  quietly: "🤫",
  whisper: "🤫",
  hidden: "🤫",
  sleep: "😴",
  sleeping: "😴",
  tired: "😴",
  exhausted: "😴",
  lazy: "😴",
  boring: "😴",
  dream: "💭",
  dreams: "💭",
  dreaming: "💭",
  hope: "💭",
  wish: "💭",

  // --- Tech / digital ---
  phone: "📱",
  app: "📱",
  mobile: "📱",
  screen: "📱",
  computer: "💻",
  laptop: "💻",
  code: "💻",
  coding: "💻",
  programming: "💻",
  software: "💻",
  tech: "💻",
  technology: "💻",
  ai: "🤖",
  robot: "🤖",
  artificial: "🤖",
  algorithm: "🤖",
  automation: "🤖",
  internet: "🌐",
  online: "🌐",
  website: "🌐",
  digital: "🌐",
  social: "📲",
  media: "📲",
  instagram: "📲",
  youtube: "📲",
  tiktok: "📲",
  twitter: "📲",
  viral: "📲",
  followers: "📲",
  subscribers: "📲",
  content: "📲",
  video: "🎬",
  videos: "🎬",
  film: "🎬",
  camera: "📸",
  photo: "📸",
  picture: "📸",
  image: "📸",
  selfie: "📸",
  game: "🎮",
  games: "🎮",
  gaming: "🎮",
  player: "🎮",
  play: "🎮",
  playing: "🎮",

  // --- Food / drink ---
  food: "🍕",
  eat: "🍕",
  eating: "🍕",
  hungry: "🍕",
  meal: "🍕",
  dinner: "🍕",
  lunch: "🍕",
  breakfast: "🍕",
  delicious: "🍕",
  tasty: "🍕",
  yummy: "🍕",
  coffee: "☕",
  tea: "☕",
  drink: "🍺",
  drinking: "🍺",
  beer: "🍺",
  wine: "🍷",
  cheers: "🥂",
  toast: "🥂",
  water: "💧",

  // --- Time / speed ---
  time: "⏰",
  clock: "⏰",
  hour: "⏰",
  hours: "⏰",
  minute: "⏰",
  minutes: "⏰",
  deadline: "⏰",
  today: "📅",
  tomorrow: "📅",
  yesterday: "📅",
  year: "📅",
  years: "📅",
  month: "📅",
  fast: "⚡",
  quick: "⚡",
  quickly: "⚡",
  speed: "⚡",
  instant: "⚡",
  immediately: "⚡",
  rapid: "⚡",
  lightning: "⚡",
  boom: "💥",
  bang: "💥",
  explode: "💥",
  explosion: "💥",
  blast: "💥",
  impact: "💥",

  // --- People / relationships ---
  family: "👨‍👩‍👧‍👦",
  friends: "👫",
  friend: "👫",
  friendship: "👫",
  buddy: "👫",
  together: "👫",
  team: "👥",
  group: "👥",
  community: "👥",
  people: "👥",
  everyone: "👥",
  audience: "👥",
  baby: "👶",
  kid: "👶",
  kids: "👶",
  children: "👶",
  child: "👶",
  boy: "👦",
  girl: "👧",
  man: "👨",
  woman: "👩",

  // --- Nature / world ---
  world: "🌍",
  earth: "🌍",
  global: "🌍",
  planet: "🌍",
  country: "🌍",
  nature: "🌿",
  tree: "🌳",
  trees: "🌳",
  forest: "🌳",
  flower: "🌸",
  flowers: "🌸",
  sun: "☀️",
  sunny: "☀️",
  sunshine: "☀️",
  rain: "🌧️",
  raining: "🌧️",
  storm: "⛈️",
  snow: "❄️",
  cold: "🥶",
  freezing: "🥶",
  ocean: "🌊",
  sea: "🌊",
  wave: "🌊",
  waves: "🌊",
  beach: "🏖️",
  mountain: "⛰️",
  mountains: "⛰️",
  animal: "🐾",
  animals: "🐾",
  dog: "🐕",
  cat: "🐈",

  // --- Direction / emphasis ---
  first: "☝️",
  number: "☝️",
  one: "1️⃣",
  two: "2️⃣",
  three: "3️⃣",
  four: "4️⃣",
  five: "5️⃣",
  ten: "🔟",
  eyes: "👀",
  look: "👀",
  watch: "👀",
  see: "👀",
  notice: "👀",
  attention: "👀",
  stare: "👀",
  point: "👉",
  here: "👉",
  this: "👉",
  check: "✅",
  correct: "✅",
  yes: "✅",
  true: "✅",
  done: "✅",
  finished: "✅",
  complete: "✅",
  tip: "💡",
  tips: "💡",
  trick: "💡",
  tricks: "💡",
  hack: "💡",
  hacks: "💡",
  key: "🔑",
  keys: "🔑",
  unlock: "🔑",
  open: "🔑",
  important: "‼️",
  crucial: "‼️",
  critical: "‼️",
  essential: "‼️",
  must: "‼️",
  remember: "📌",
  note: "📌",
  save: "📌",
  bookmark: "📌",
  free: "🆓",
  freedom: "🗽",

  // --- Health / body ---
  health: "💚",
  healthy: "💚",
  fitness: "💚",
  diet: "💚",
  exercise: "💚",
  run: "🏃",
  running: "🏃",
  walk: "🚶",
  walking: "🚶",
  ill: "🤒",
  doctor: "🏥",
  hospital: "🏥",
  medicine: "💊",

  // --- Home / places ---
  home: "🏠",
  house: "🏠",
  apartment: "🏠",
  room: "🏠",
  door: "🚪",
  school: "🏫",
  college: "🎓",
  university: "🎓",
  graduate: "🎓",
  graduation: "🎓",
  education: "🎓",
  city: "🏙️",
  travel: "✈️",
  traveling: "✈️",
  trip: "✈️",
  flight: "✈️",
  vacation: "✈️",
  car: "🚗",
  drive: "🚗",
  driving: "🚗",

  // --- Music / art ---
  music: "🎵",
  song: "🎵",
  singing: "🎵",
  sing: "🎵",
  dance: "💃",
  dancing: "💃",
  art: "🎨",
  artist: "🎨",
  design: "🎨",
  paint: "🎨",
  painting: "🎨",
  draw: "🎨",
  drawing: "🎨",

  // --- Misc intensifiers ---
  literally: "💯",
  actually: "☝️",
  basically: "☝️",
  honestly: "💯",
  obviously: "🙄",
  definitely: "💯",
  completely: "💯",
  totally: "💯",
  massive: "🔥",
  huge: "🔥",
  enormous: "🔥",
  giant: "🔥",
  tiny: "🤏",
  small: "🤏",
  little: "🤏",
};

// Phrase patterns checked before single words — captures context
const PHRASE_MAP: [string[], string][] = [
  // Negation-aware: "not X" or "don't X" flips the emoji
  [["not", "happy"], "😢"],
  [["not", "good"], "👎"],
  [["not", "bad"], "✅"],
  [["not", "kidding"], "😳"],
  [["no", "way"], "🤯"],
  [["no", "joke"], "😳"],
  [["no", "cap"], "💯"],

  // Multi-word expressions
  [["on", "fire"], "🔥"],
  [["let's", "go"], "🚀"],
  [["lets", "go"], "🚀"],
  [["game", "changer"], "🏆"],
  [["game", "over"], "💀"],
  [["next", "level"], "🚀"],
  [["level", "up"], "📈"],
  [["blow", "up"], "💥"],
  [["blew", "up"], "💥"],
  [["break", "down"], "📊"],
  [["broke", "down"], "😢"],
  [["give", "up"], "🛑"],
  [["gave", "up"], "🛑"],
  [["wake", "up"], "⏰"],
  [["work", "out"], "💪"],
  [["figure", "out"], "💡"],
  [["find", "out"], "👀"],
  [["turn", "around"], "🔄"],
  [["stand", "out"], "✨"],
  [["show", "up"], "💪"],
  [["shut", "up"], "🤫"],
  [["hold", "on"], "🛑"],
  [["hang", "on"], "🛑"],
  [["come", "on"], "😤"],
  [["bring", "it"], "💪"],
  [["keep", "going"], "💪"],
  [["keep", "pushing"], "💪"],
  [["stay", "focused"], "🎯"],
  [["pay", "attention"], "👀"],
  [["real", "talk"], "💯"],
  [["plot", "twist"], "🤯"],
  [["pro", "tip"], "💡"],
  [["fun", "fact"], "🤓"],
  [["side", "hustle"], "💰"],
  [["make", "money"], "💰"],
  [["lose", "money"], "📉"],
  [["lost", "money"], "📉"],
  [["go", "viral"], "📲"],
  [["went", "viral"], "📲"],
  [["broke", "the", "internet"], "💥"],
  [["oh", "my", "god"], "😱"],
  [["what", "the"], "😳"],
  [["are", "you", "serious"], "🤨"],
  [["i", "promise"], "🤞"],
  [["trust", "me"], "🤝"],
  [["believe", "me"], "🤝"],
  [["watch", "this"], "👀"],
  [["look", "at", "this"], "👀"],
  [["check", "this", "out"], "👀"],
  [["by", "the", "way"], "☝️"],
  [["at", "the", "end"], "🏁"],
  [["in", "the", "end"], "🏁"],
  [["first", "of", "all"], "☝️"],
  [["once", "upon"], "📖"],
  [["long", "story"], "📖"],
  [["true", "story"], "💯"],
  [["hot", "take"], "🔥"],
  [["drop", "the", "mic"], "🎤"],
  [["mic", "drop"], "🎤"],
  [["sneak", "peek"], "👀"],
  [["behind", "the", "scenes"], "🎬"],
  [["red", "flag"], "🚩"],
  [["green", "flag"], "💚"],
  [["full", "send"], "🚀"],
  [["built", "different"], "😤"],
  [["hits", "different"], "✨"],
  [["not", "gonna", "lie"], "💯"],
  [["i", "swear"], "🤞"],
  [["for", "real"], "💯"],
  [["high", "quality"], "💎"],
  [["top", "tier"], "👑"],
  [["old", "school"], "🎓"],
  [["brand", "new"], "✨"],
  [["hard", "work"], "💪"],
  [["big", "deal"], "‼️"],
  [["number", "one"], "🥇"],
];

export function findEmoji(words: string[]): string | undefined {
  const lowerWords = words.map((w) => w.toLowerCase().replace(/[^a-z]/g, ""));
  const joined = lowerWords.join(" ");

  // Check phrases first (context-aware)
  for (const [phrase, emoji] of PHRASE_MAP) {
    const phraseStr = phrase.join(" ");
    if (joined.includes(phraseStr)) {
      return emoji;
    }
  }

  // Fall back to single-word matching
  for (const w of lowerWords) {
    if (EMOJI_MAP[w]) {
      return EMOJI_MAP[w];
    }
  }
  return undefined;
}
