// ABOUTME: Template configurations for 10 visual cue motion design archetypes
// ABOUTME: 4 original + 6 new styles with distinct layout, animation, and feel

import type { CueStyle, VisualCueTemplate } from "./types";

export const VISUAL_TEMPLATES: Record<CueStyle, VisualCueTemplate> = {
  cinematic: {
    layout: "card",
    cardWidth: 280,
    borderRadius: 20,
    padding: 28,
    background: "rgba(0, 0, 0, 0.7)",
    backdropBlur: 40,
    border: "1px solid rgba(255, 255, 255, 0.15)",
    boxShadow:
      "0 8px 40px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.1)",
    accentBar: true,
    accentWidth: 3,
    underline: false,
    iconBackground: false,
    iconGlow: true,
    titleWeight: 700,
    titleSize: 20,
    valueSize: 42,
    textShadow: "none",
    entranceType: "slide-reveal",
    entranceSpring: { damping: 80, stiffness: 200 },
    idleAnimation: "float",
    exitFrames: 15,
  },

  bold: {
    layout: "card",
    cardWidth: 280,
    borderRadius: 24,
    padding: 28,
    background: "linear-gradient(135deg, {color}, {colorDark})",
    backdropBlur: 0,
    border: "none",
    boxShadow: "0 12px 40px {colorShadow}",
    accentBar: false,
    accentWidth: 0,
    underline: false,
    iconBackground: true,
    iconGlow: false,
    titleWeight: 800,
    titleSize: 22,
    valueSize: 48,
    textShadow: "none",
    entranceType: "scale-bounce",
    entranceSpring: { damping: 8, stiffness: 250 },
    idleAnimation: "pulse",
    exitFrames: 12,
  },

  broadcast: {
    layout: "bar",
    cardWidth: 420,
    borderRadius: 0,
    padding: 16,
    background: "rgba(15, 23, 42, 0.95)",
    backdropBlur: 0,
    border: "none",
    boxShadow: "0 4px 20px rgba(0,0,0,0.4)",
    accentBar: true,
    accentWidth: 4,
    underline: false,
    iconBackground: false,
    iconGlow: false,
    titleWeight: 600,
    titleSize: 18,
    valueSize: 32,
    textShadow: "none",
    entranceType: "wipe",
    entranceSpring: { damping: 20, stiffness: 300 },
    idleAnimation: "none",
    exitFrames: 12,
  },

  minimal: {
    layout: "text",
    cardWidth: 280,
    borderRadius: 0,
    padding: 16,
    background: "none",
    backdropBlur: 0,
    border: "none",
    boxShadow: "none",
    accentBar: false,
    accentWidth: 0,
    underline: true,
    iconBackground: false,
    iconGlow: false,
    titleWeight: 600,
    titleSize: 20,
    valueSize: 40,
    textShadow: "0 2px 8px rgba(0,0,0,0.8), 0 0 30px rgba(0,0,0,0.5)",
    entranceType: "fade-slide",
    entranceSpring: { damping: 30, stiffness: 150 },
    idleAnimation: "none",
    exitFrames: 12,
  },

  // --- New styles ---

  glass: {
    layout: "card",
    cardWidth: 300,
    borderRadius: 24,
    padding: 28,
    background: "rgba(255, 255, 255, 0.08)",
    backdropBlur: 60,
    border: "1px solid rgba(255, 255, 255, 0.2)",
    boxShadow:
      "0 8px 32px rgba(0,0,0,0.2), inset 0 1px 0 rgba(255,255,255,0.15)",
    accentBar: false,
    accentWidth: 0,
    underline: false,
    iconBackground: false,
    iconGlow: true,
    titleWeight: 500,
    titleSize: 19,
    valueSize: 40,
    textShadow: "none",
    entranceType: "blur-reveal",
    entranceSpring: { damping: 30, stiffness: 180 },
    idleAnimation: "breathe",
    exitFrames: 18,
    exitType: "blur-out",
    secondaryMotion: "shimmer",
    fontFamily: "SF Pro Display, Inter, system-ui, sans-serif",
  },

  neon: {
    layout: "card",
    cardWidth: 300,
    borderRadius: 12,
    padding: 24,
    background: "rgba(0, 0, 0, 0.85)",
    backdropBlur: 0,
    border: "1px solid {color}",
    boxShadow: "0 0 20px {colorShadow}, inset 0 0 20px rgba(0,0,0,0.5)",
    accentBar: false,
    accentWidth: 0,
    underline: false,
    iconBackground: false,
    iconGlow: true,
    titleWeight: 700,
    titleSize: 20,
    valueSize: 44,
    textShadow: "0 0 10px {colorShadow}",
    entranceType: "flicker",
    entranceSpring: { damping: 15, stiffness: 300 },
    idleAnimation: "glow-pulse",
    exitFrames: 12,
    exitType: "flicker-out",
    secondaryMotion: "border-trace",
    fontFamily: "Inter, system-ui, sans-serif",
  },

  editorial: {
    layout: "card",
    cardWidth: 320,
    borderRadius: 0,
    padding: 32,
    background: "rgba(20, 20, 30, 0.92)",
    backdropBlur: 20,
    border: "none",
    boxShadow: "0 2px 20px rgba(0,0,0,0.3)",
    accentBar: true,
    accentWidth: 3,
    accentPosition: "top",
    underline: false,
    iconBackground: false,
    iconGlow: false,
    titleWeight: 300,
    titleSize: 22,
    valueSize: 48,
    textShadow: "none",
    entranceType: "clip-reveal",
    entranceSpring: { damping: 25, stiffness: 200 },
    idleAnimation: "none",
    exitFrames: 15,
    fontFamily: "'Georgia', 'Times New Roman', serif",
  },

  sports: {
    layout: "bar",
    cardWidth: 400,
    borderRadius: 4,
    padding: 16,
    background: "linear-gradient(90deg, {color}, {colorDark})",
    backdropBlur: 0,
    border: "none",
    boxShadow: "0 6px 24px {colorShadow}",
    accentBar: false,
    accentWidth: 0,
    underline: false,
    iconBackground: false,
    iconGlow: false,
    titleWeight: 900,
    titleSize: 22,
    valueSize: 36,
    textShadow: "0 2px 4px rgba(0,0,0,0.3)",
    entranceType: "slam-in",
    entranceSpring: { damping: 6, stiffness: 400 },
    idleAnimation: "none",
    exitFrames: 8,
    skewX: -4,
    uppercase: true,
    fontFamily: "Impact, 'Arial Black', sans-serif",
  },

  social: {
    layout: "card",
    cardWidth: 240,
    borderRadius: 100,
    padding: 20,
    background: "linear-gradient(135deg, {color}, {colorDark})",
    backdropBlur: 0,
    border: "none",
    boxShadow: "0 8px 24px {colorShadow}",
    accentBar: false,
    accentWidth: 0,
    underline: false,
    iconBackground: false,
    iconGlow: false,
    titleWeight: 700,
    titleSize: 18,
    valueSize: 32,
    textShadow: "none",
    entranceType: "pop-in",
    entranceSpring: { damping: 6, stiffness: 300 },
    idleAnimation: "wiggle",
    exitFrames: 10,
    exitType: "scale-down",
    fontFamily: "Inter, system-ui, sans-serif",
  },

  tech: {
    layout: "card",
    cardWidth: 320,
    borderRadius: 4,
    padding: 24,
    background: "rgba(0, 20, 0, 0.9)",
    backdropBlur: 0,
    border: "1px solid {color}30",
    boxShadow: "0 0 30px rgba(0,0,0,0.5)",
    accentBar: false,
    accentWidth: 0,
    underline: false,
    iconBackground: false,
    iconGlow: true,
    titleWeight: 400,
    titleSize: 18,
    valueSize: 38,
    textShadow: "0 0 8px {colorShadow}",
    entranceType: "typewriter",
    entranceSpring: { damping: 20, stiffness: 200 },
    idleAnimation: "scan-line",
    exitFrames: 12,
    secondaryMotion: "border-trace",
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    uppercase: false,
  },
};
